### ISSUE TITLE
Validating problem

### ISSUE THREAD

**Issue by Steven0928** [megvii-research/OccDepth#10]
Hi,
  I noticed that when training reach about 80~90 percent there will be a validating process, what dose the process validate about? 
  Dose the validate result desides the epoch result?
 Thanks,looking forward to your reply

**Comment by Steven0928** [comment]
BTW , my epoch is running 14 but my last.ckpt version is noly 3 . how is that happen

**Comment by rhmiao** [comment]
The code will only save top-k ckpts.  And validation is an independent process, it would not affect training.
