### ISSUE TITLE
Key 'data_root' is not in struct

### ISSUE THREAD

**Issue by Jessy-Huang** [megvii-research/OccDepth#2]
运行process.py时遇到如下报错，config文件中做了相应的修改，运行还是报错
Traceback (most recent call last):
  File "/media/hjc/DeepLearning1/DLProjects/Robot-binocular-vision/OccDepth/occdepth/data/NYU/preprocess.py", line 150, in main
    root = os.path.join(config.data_root, "NYU" + split)
omegaconf.errors.ConfigAttributeError: Key 'data_root' is not in struct
	full_key: data_root
	reference_type=Optional[Dict[Union[str, Enum], Any]]
	object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by chensiweiTHU** [comment]
巧了，我也遇到了这个问题

**Comment by chensiweiTHU** [comment]
应该是hydra载入参数时要用到环境变量的 问题，我在preprocess.py的149行改成了手动载入config_path和name两个参数，写的绝对路径就可以了

**Comment by rhmiao** [comment]
thx, this issue is fixed in [d5dec44](https://github.com/megvii-research/OccDepth/commit/d5dec44c2313ce8fc2cc70c579ea197eede6d492)
