### ISSUE TITLE
Can't install mmcv properly.  

### ISSUE THREAD

**Issue by JohnFuguiWang** [megvii-research/OccDepth#4]
# Environment
ubuntu 20.04
cuda 10.2.89
pytorch 1.13.1

# Problem
According to the requirement.txt, the version of mmcv is 1.4.0, which seems to be a very old version. I've read the official document of MMCV, bu I still find it hard to install mmcv 1.4.0 that matches pytorch 1.13.1 and cuda 10.2. 
I wonder could anybody please kindly post his environment and his approach to install mmcv? Thanks a lot :)

**Comment by rhmiao** [comment]
mmcv-full 1.7.0 also works well. @JohnFuguiWang

**Comment by Jessy-Huang** [comment]
I also met with this problem，even if I install mmcv from source code

**Comment by Real-YuZhe** [comment]
> mmcv-full 1.7.0 also works well. @JohnFuguiWang

Could you provide your OS version and hardware info? I also have trouble in env configuration.

**Comment by rhmiao** [comment]
os ： Ubuntu 20.04.4 LTS
python:  3.7.13
cuda:  11.7
torch:  1.13.0+cu117
mmcv: 1.7.0
@Real-YuZhe

**Comment by JohnFuguiWang** [comment]
I think the problem is solved. My solution is that I chose the version of pytorch and mmcv following another repository "VoxFormer", while other library versions can be settled following OccDepth.  @Louis-Leee proposed this idea and I really appreciate it.  
Also, the authorized environment has been posted by rhmiao in this issue. Thank him for his respond.
