### ISSUE TITLE
trained models(NYU_multicam_flospdepth_crp_stereodepth_cascadecls_2080ti_mIoU29.0.ckpt) is not match with model struct

### ISSUE THREAD

**Issue by xyzhou-dev** [megvii-research/OccDepth#6]
test steps:
- source env_NYU.sh
- python occdepth/scripts/generate_output.py n_gpus=4 batch_size_per_gpu=1
---
![image](https://user-images.githubusercontent.com/130032157/230287366-e6002756-20e9-435b-9fff-cf1e00300a60.png)
NYU ckpt(NYU_multicam_flospdepth_crp_stereodepth_cascadecls_2080ti_mIoU29.0.ckpt) download from [model](https://drive.google.com/file/d/1tBKB-J6NAxDTRTOE1hwAacRmwu57q8L8/view?usp=share_link)
NYU....ckpt md5 98b0e5eb0b6f6e67e4f8c00d35578b9a
commit 6d483fc5123ac362e52240bcca6a507f4c774b23

**Comment by rhmiao** [comment]
@xyzhou-dev   `cascade_cls` and `context_prior` in config should be set as false with [NYU_multicam_flospdepth_crp_stereodepth_cascadecls_2080ti_mIoU29.0.ckpt](https://drive.google.com/file/d/1tBKB-J6NAxDTRTOE1hwAacRmwu57q8L8/view?usp=share_link), we  fix it in [fix config and eval of NYUv2](https://github.com/megvii-research/OccDepth/commit/a8456da4e70a5fde48cec4d9ca44625c827bac79)

**Comment by xyzhou-dev** [comment]
thanks very much, basically it's work now
![image](https://user-images.githubusercontent.com/130032157/230575434-e484682b-a809-4b07-b868-0620883c5aa1.png)
